# These are supported funding model platforms

PLEASE, write electronic mail to: ahzlimat@outlook.com and >

> (please, try for: NOT jokes/adversiting/boredPeople/tecnical/researchers/educational or other business or questions for all my personal code, projects o subjects)
THANKs YOU !
