//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWPAPZ000._000.addclick2.textoamp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_MP3s
    {
        public System.Guid id { get; set; }
        public string mail { get; set; }
        public string titulo { get; set; }
        public string url { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fecha { get; set; }
        public bool borrado { get; set; }
    }
}
