//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class universalsemiotics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal universalsemiotics() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.universalsemiotics", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string cerrar_sesion {
            get {
                return ResourceManager.GetString("cerrar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contacto.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string contacto_titulo {
            get {
                return ResourceManager.GetString("contacto_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contrasenia {
            get {
                return ResourceManager.GetString("contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string contrasenia_confirmar {
            get {
                return ResourceManager.GetString("contrasenia_confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña reestablecida.
        /// </summary>
        internal static string contrasenia_reestablecida {
            get {
                return ResourceManager.GetString("contrasenia_reestablecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es.
        /// </summary>
        internal static string controlador {
            get {
                return ResourceManager.GetString("controlador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string correo_electronico {
            get {
                return ResourceManager.GetString("correo_electronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descargas.
        /// </summary>
        internal static string descargas {
            get {
                return ResourceManager.GetString("descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargas.
        /// </summary>
        internal static string descargas_titulo {
            get {
                return ResourceManager.GetString("descargas_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversor de texto a voz, pasa tu PDF o texto a mp3 y escúchalo, Web Online.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico CONFIRMADO.
        /// </summary>
        internal static string email_confirmado {
            get {
                return ResourceManager.GetString("email_confirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por confirmar su correo electrónico..
        /// </summary>
        internal static string email_confirmado_gracias {
            get {
                return ResourceManager.GetString("email_confirmado_gracias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar correo electrónico.
        /// </summary>
        internal static string email_enviar {
            get {
                return ResourceManager.GetString("email_enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a su e-mail no está confirmado, por favor, confírmelo primero.
        /// </summary>
        internal static string email_no_confirmado {
            get {
                return ResourceManager.GetString("email_no_confirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a enlaces patrocinados.
        /// </summary>
        internal static string enlaces_patrocinados {
            get {
                return ResourceManager.GetString("enlaces_patrocinados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string iniciar_sesion {
            get {
                return ResourceManager.GetString("iniciar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haga clic aquí para iniciar sesión.
        /// </summary>
        internal static string iniciar_sesion_click {
            get {
                return ResourceManager.GetString("iniciar_sesion_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ha olvidado su contraseña?.
        /// </summary>
        internal static string olvido_contrasenia {
            get {
                return ResourceManager.GetString("olvido_contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a texto a voz,texto a mp3, texto a audio.
        /// </summary>
        internal static string palabras_clave {
            get {
                return ResourceManager.GetString("palabras_clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicidad.
        /// </summary>
        internal static string publicidad {
            get {
                return ResourceManager.GetString("publicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reCaptcha Inválido.
        /// </summary>
        internal static string recaptcha_invalid {
            get {
                return ResourceManager.GetString("recaptcha_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Recordar cuenta?.
        /// </summary>
        internal static string recuerdame {
            get {
                return ResourceManager.GetString("recuerdame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string registrarse {
            get {
                return ResourceManager.GetString("registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        internal static string restablecer {
            get {
                return ResourceManager.GetString("restablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        internal static string restablecer_contrasenia {
            get {
                return ResourceManager.GetString("restablecer_contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a texto_a_voz.
        /// </summary>
        internal static string texto_a_voz {
            get {
                return ResourceManager.GetString("texto_a_voz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a texto_a_voz_pro.
        /// </summary>
        internal static string texto_a_voz_pro {
            get {
                return ResourceManager.GetString("texto_a_voz_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversión Profesional.
        /// </summary>
        internal static string texto_a_voz_pro_titulo {
            get {
                return ResourceManager.GetString("texto_a_voz_pro_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversión GRaTuiTa.
        /// </summary>
        internal static string texto_a_voz_titulo {
            get {
                return ResourceManager.GetString("texto_a_voz_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse como usuario nuevo.
        /// </summary>
        internal static string usuario_nuevo {
            get {
                return ResourceManager.GetString("usuario_nuevo", resourceCulture);
            }
        }
    }
}
