'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class universalsemiotics
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UWP000.universalsemiotics", GetType(universalsemiotics).GetTypeInfo.Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cerrar sesión.
    '''</summary>
    Friend Shared ReadOnly Property cerrar_sesion() As String
        Get
            Return ResourceManager.GetString("cerrar_sesion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a contacto.
    '''</summary>
    Friend Shared ReadOnly Property contacto() As String
        Get
            Return ResourceManager.GetString("contacto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Contacto.
    '''</summary>
    Friend Shared ReadOnly Property contacto_titulo() As String
        Get
            Return ResourceManager.GetString("contacto_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Contraseña.
    '''</summary>
    Friend Shared ReadOnly Property contrasenia() As String
        Get
            Return ResourceManager.GetString("contrasenia", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Confirmar contraseña.
    '''</summary>
    Friend Shared ReadOnly Property contrasenia_confirmar() As String
        Get
            Return ResourceManager.GetString("contrasenia_confirmar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Contraseña reestablecida.
    '''</summary>
    Friend Shared ReadOnly Property contrasenia_reestablecida() As String
        Get
            Return ResourceManager.GetString("contrasenia_reestablecida", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a es.
    '''</summary>
    Friend Shared ReadOnly Property controlador() As String
        Get
            Return ResourceManager.GetString("controlador", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Correo electrónico.
    '''</summary>
    Friend Shared ReadOnly Property correo_electronico() As String
        Get
            Return ResourceManager.GetString("correo_electronico", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a descargas.
    '''</summary>
    Friend Shared ReadOnly Property descargas() As String
        Get
            Return ResourceManager.GetString("descargas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Descargas.
    '''</summary>
    Friend Shared ReadOnly Property descargas_titulo() As String
        Get
            Return ResourceManager.GetString("descargas_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Conversor de texto a voz, pasa tu PDF o texto a mp3 y escúchalo, Web Online.
    '''</summary>
    Friend Shared ReadOnly Property descripcion() As String
        Get
            Return ResourceManager.GetString("descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Correo electrónico CONFIRMADO.
    '''</summary>
    Friend Shared ReadOnly Property email_confirmado() As String
        Get
            Return ResourceManager.GetString("email_confirmado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Gracias por confirmar su correo electrónico..
    '''</summary>
    Friend Shared ReadOnly Property email_confirmado_gracias() As String
        Get
            Return ResourceManager.GetString("email_confirmado_gracias", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Enviar correo electrónico.
    '''</summary>
    Friend Shared ReadOnly Property email_enviar() As String
        Get
            Return ResourceManager.GetString("email_enviar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a su e-mail no está confirmado, por favor, confírmelo primero.
    '''</summary>
    Friend Shared ReadOnly Property email_no_confirmado() As String
        Get
            Return ResourceManager.GetString("email_no_confirmado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a enlaces patrocinados.
    '''</summary>
    Friend Shared ReadOnly Property enlaces_patrocinados() As String
        Get
            Return ResourceManager.GetString("enlaces_patrocinados", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Iniciar sesión.
    '''</summary>
    Friend Shared ReadOnly Property iniciar_sesion() As String
        Get
            Return ResourceManager.GetString("iniciar_sesion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Haga clic aquí para iniciar sesión.
    '''</summary>
    Friend Shared ReadOnly Property iniciar_sesion_click() As String
        Get
            Return ResourceManager.GetString("iniciar_sesion_click", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Ha olvidado su contraseña?.
    '''</summary>
    Friend Shared ReadOnly Property olvido_contrasenia() As String
        Get
            Return ResourceManager.GetString("olvido_contrasenia", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a texto a voz,texto a mp3, texto a audio.
    '''</summary>
    Friend Shared ReadOnly Property palabras_clave() As String
        Get
            Return ResourceManager.GetString("palabras_clave", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Publicidad.
    '''</summary>
    Friend Shared ReadOnly Property publicidad() As String
        Get
            Return ResourceManager.GetString("publicidad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a reCaptcha Inválido.
    '''</summary>
    Friend Shared ReadOnly Property recaptcha_invalid() As String
        Get
            Return ResourceManager.GetString("recaptcha_invalid", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Recordar cuenta?.
    '''</summary>
    Friend Shared ReadOnly Property recuerdame() As String
        Get
            Return ResourceManager.GetString("recuerdame", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Registrarse.
    '''</summary>
    Friend Shared ReadOnly Property registrarse() As String
        Get
            Return ResourceManager.GetString("registrarse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Restablecer.
    '''</summary>
    Friend Shared ReadOnly Property restablecer() As String
        Get
            Return ResourceManager.GetString("restablecer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Restablecer contraseña.
    '''</summary>
    Friend Shared ReadOnly Property restablecer_contrasenia() As String
        Get
            Return ResourceManager.GetString("restablecer_contrasenia", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a texto_a_voz.
    '''</summary>
    Friend Shared ReadOnly Property texto_a_voz() As String
        Get
            Return ResourceManager.GetString("texto_a_voz", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a texto_a_voz_pro.
    '''</summary>
    Friend Shared ReadOnly Property texto_a_voz_pro() As String
        Get
            Return ResourceManager.GetString("texto_a_voz_pro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Conversión Profesional.
    '''</summary>
    Friend Shared ReadOnly Property texto_a_voz_pro_titulo() As String
        Get
            Return ResourceManager.GetString("texto_a_voz_pro_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Conversión GRaTuiTa.
    '''</summary>
    Friend Shared ReadOnly Property texto_a_voz_titulo() As String
        Get
            Return ResourceManager.GetString("texto_a_voz_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Registrarse como usuario nuevo.
    '''</summary>
    Friend Shared ReadOnly Property usuario_nuevo() As String
        Get
            Return ResourceManager.GetString("usuario_nuevo", resourceCulture)
        End Get
    End Property
End Class
