//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AspNetUsers
{
    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }
}

public partial class Mp3Free
{
    public System.Guid Id { get; set; }
    public System.Guid UserId { get; set; }
    public string titulo { get; set; }
    public string idioma { get; set; }
    public long caracteres { get; set; }
    public Nullable<bool> estado { get; set; }
    public System.DateTime fechaIni { get; set; }
    public Nullable<System.DateTime> fechaFin { get; set; }
}

public partial class Mp3Pro
{
    public System.Guid Id { get; set; }
    public System.Guid UserId { get; set; }
    public string titulo { get; set; }
    public string idioma { get; set; }
    public long caracteres { get; set; }
    public Nullable<bool> estado { get; set; }
    public System.DateTime fechaIni { get; set; }
    public Nullable<System.DateTime> fechaFin { get; set; }
}

public partial class PublicidadBanner
{
    public System.Guid IdPubli { get; set; }
    public System.Guid IdUser { get; set; }
    public System.DateTime fechaIni { get; set; }
    public string titulo { get; set; }
    public string banner { get; set; }
    public string extension { get; set; }
    public bool validado { get; set; }
    public bool publicado { get; set; }
    public string urlD { get; set; }
}

public partial class PublicidadBannerPago
{
    public System.Guid Id { get; set; }
    public System.Guid IdPubli { get; set; }
    public System.DateTime fechaIni { get; set; }
    public System.DateTime fechaFin { get; set; }
    public decimal importe { get; set; }
}

public partial class UsersData
{
    public System.Guid UserId { get; set; }
    public long caracteres { get; set; }
}
