//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWPAPZ000._000.universalsemiotics.universalsemiotics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mp3Free
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string titulo { get; set; }
        public string idioma { get; set; }
        public long caracteres { get; set; }
        public Nullable<bool> estado { get; set; }
        public System.DateTime fechaIni { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    }
}
