//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWPAPZ000._000.universalsemiotics.universalsemiotics
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicidadBannerPago
    {
        public System.Guid Id { get; set; }
        public System.Guid IdPubli { get; set; }
        public System.DateTime fechaIni { get; set; }
        public System.DateTime fechaFin { get; set; }
        public decimal importe { get; set; }
    }
}
