//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWPAPZ000._000.addclick2.apzyxService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_MP3
    {
        public System.Guid id { get; set; }
        public System.Guid id_User { get; set; }
        public string titulo { get; set; }
        public string url { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual User User { get; set; }
    }
}
