//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Users_MP3 = new HashSet<Users_MP3>();
    }

    public string u { get; set; }
    public string d { get; set; }
    public System.Guid id { get; set; }

    public virtual Users_Data Users_Data { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Users_MP3> Users_MP3 { get; set; }
}

public partial class Users_Data
{
    public System.Guid id { get; set; }
    public string nombre { get; set; }
    public byte[] password { get; set; }
    public decimal prices { get; set; }

    public virtual User User { get; set; }
}

public partial class Users_MP3
{
    public System.Guid id { get; set; }
    public System.Guid id_User { get; set; }
    public string titulo { get; set; }
    public string url { get; set; }
    public Nullable<decimal> precio { get; set; }

    public virtual User User { get; set; }
}
