//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWPAPZ000._000.addclick2.addclickService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Data
    {
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public byte[] password { get; set; }
        public decimal prices { get; set; }
    
        public virtual User User { get; set; }
    }
}
