<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>es-ES</DefaultLanguage>
    <PublishAot>true</PublishAot>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <EnableMsixTooling>true</EnableMsixTooling>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="000\666 way\666 way\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_637424743200000000.json" />
    <Content Include="000\666way\.vs\666way\v17\DocumentLayout.backup.json" />
    <Content Include="000\666way\.vs\666way\v17\DocumentLayout.json" />
    <Content Include="000\addclick2\textoamp3app\textoamp3app.UWP\obj\x86\Debug\.winmd_cache\$Microsoft.Graphics.Canvas.winmd_636160679180000000.json" />
    <Content Include="000\addclick2\textoamp3app\textoamp3app.UWP\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_636885238160000000.json" />
    <Content Include="000\apzMadmanHill\.vs\VSWorkspaceState.json" />
    <Content Include="000\apzyxGames\.vs\apzyxGames\v17\DocumentLayout.backup.json" />
    <Content Include="000\apzyxGames\.vs\apzyxGames\v17\DocumentLayout.json" />
    <Content Include="000\apzyxGames\apzyxGames\.vs\apzyxGames.csproj.dtbcache.json" />
    <Content Include="000\apzyxGames\apzyxGames\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_638316334480000000.json" />
    <Content Include="000\apzyxGames\apzyxGames\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_638441419520000000.json" />
    <Content Include="000\apz_Image_Editor\.vs\apz_Image_Editor\v17\DocumentLayout.backup.json" />
    <Content Include="000\apz_Image_Editor\.vs\apz_Image_Editor\v17\DocumentLayout.json" />
    <Content Include="000\bitcoinCoreMiner\.vs\bitcoinCoreMiner\v17\DocumentLayout.backup.json" />
    <Content Include="000\bitcoinCoreMiner\.vs\bitcoinCoreMiner\v17\DocumentLayout.json" />
    <Content Include="000\BIT_IMG\.vs\BIT_IMG\v17\DocumentLayout.backup.json" />
    <Content Include="000\BIT_IMG\.vs\BIT_IMG\v17\DocumentLayout.json" />
    <Content Include="000\BIT_IMG\BIT_IMG\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_637934986560000000.json" />
    <Content Include="000\CWalletSearch\.vs\CWalletSearch\v17\DocumentLayout.backup.json" />
    <Content Include="000\CWalletSearch\.vs\CWalletSearch\v17\DocumentLayout.json" />
    <Content Include="000\FarmsWar\.vs\FarmsWar\project-colors.json" />
    <Content Include="000\FarmsWar\.vs\FarmsWar\v17\DocumentLayout.json" />
    <Content Include="000\FarmsWar\apzyxGameService\.vs\apzyxGameService.csproj.dtbcache.json" />
    <Content Include="000\FarmsWar\apzyxGames\.vs\apzyxGames.csproj.dtbcache.json" />
    <Content Include="000\FarmsWar\FarmsWar\.vs\FarmsWar.csproj.dtbcache.json" />
    <Content Include="000\FileToVideo_VideoToFile\.vs\FileToVideo_VideoToFile\v17\DocumentLayout.backup.json" />
    <Content Include="000\FileToVideo_VideoToFile\.vs\FileToVideo_VideoToFile\v17\DocumentLayout.json" />
    <Content Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\obj\x86\Debug\.winmd_cache\$Microsoft.Graphics.Canvas.winmd_637552364420000000.json" />
    <Content Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_637424743200000000.json" />
    <Content Include="000\Golden Way\.vs\VSWorkspaceState.json" />
    <Content Include="000\Golden Way\Golden Way\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_637424743200000000.json" />
    <Content Include="000\Golden Way\TokensWay\.config\dotnet-tools.json" />
    <Content Include="000\GOTCHA\.vs\GOTCHA\v17\DocumentLayout.backup.json" />
    <Content Include="000\GOTCHA\.vs\GOTCHA\v17\DocumentLayout.json" />
    <Content Include="000\GOTCHA\GOTCHA\obj\x64\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_638316334480000000.json" />
    <Content Include="000\GOTCHA\GOTCHA\obj\x64\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_638441419520000000.json" />
    <Content Include="000\GOTCHA\GOTCHA\obj\x86\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_638316334480000000.json" />
    <Content Include="000\Maths\.vs\Maths\v17\DocumentLayout.json" />
    <Content Include="000\pri\.vs\pri\project-colors.json" />
    <Content Include="000\pri\.vs\pri\v17\DocumentLayout.backup.json" />
    <Content Include="000\pri\.vs\pri\v17\DocumentLayout.json" />
    <Content Include="000\pri\.vs\pri\v17\HierarchyCache.v1.txt" />
    <Content Include="000\pri\PrimesNumbersSearch\obj\x64\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_637424743200000000.json" />
    <Content Include="000\pri\TXT Great Files\obj\x64\Debug\.winmd_cache\$Microsoft.UI.Xaml.Markup.winmd_637424743200000000.json" />
    <Content Include="000\seackers\.vs\seackers\v17\DocumentLayout.json" />
    <Content Include="000\universalsemiotics\.vs\universalsemiotics\config\debuggerConfiguration-b47921dc-394e-44f3-9687-bc7e0f5e8bf9.json" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="000\666 way\666 way\bin\ARM64\Debug\" />
    <Folder Include="000\666 way\666 way\bin\ARM64\Release\" />
    <Folder Include="000\666 way\666 way\bin\ARM\Debug\" />
    <Folder Include="000\666 way\666 way\bin\ARM\Release\" />
    <Folder Include="000\666 way\666 way\bin\x64\Debug\" />
    <Folder Include="000\666 way\666 way\bin\x64\Release\" />
    <Folder Include="000\666 way\666 way\bin\x86\Release\" />
    <Folder Include="000\666 way\c666wayServ\bin\Release\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app.UWP\bin\ARM\Debug\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app.UWP\bin\ARM\Release\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app.UWP\bin\x64\Debug\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app.UWP\bin\x64\Release\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app.UWP\bin\x86\Release\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app\bin\Release\netstandard2.0\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app\obj\Debug\netstandard2.0\refint\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app\obj\Release\netstandard2.0\refint\" />
    <Folder Include="000\addclick2\textoamp3app\textoamp3app\obj\Release\netstandard2.0\ref\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\ARM64\Debug\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\ARM64\Release\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\ARM\Debug\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\ARM\Release\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\Debug\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\Release\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\x64\Debug\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\x64\Release\" />
    <Folder Include="000\apzyxGames\apzGlib\bin\x86\Release\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\ARM64\Debug\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\ARM64\Release\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\ARM\Debug\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\ARM\Release\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\x64\Debug\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\x64\Release\" />
    <Folder Include="000\apzyxGames\apzyxGames\bin\x86\Release\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\ARM64\Debug\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\ARM64\Release\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\ARM\Debug\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\ARM\Release\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\x64\Debug\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\x64\Release\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\x86\Debug\" />
    <Folder Include="000\apz_Image_Editor\apz_Image_Editor\bin\x86\Release\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\ARM64\Debug\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\ARM64\Release\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\ARM\Debug\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\ARM\Release\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\x64\Debug\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\x64\Release\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\x86\Debug\" />
    <Folder Include="000\apz_Image_Editor\testWriteable\bin\x86\Release\" />
    <Folder Include="000\bitcoinCoreMiner\bitcoinCoreMiner\bin\Debug\" />
    <Folder Include="000\bitcoinCoreMiner\bitcoinCoreMiner\bin\Release\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\ARM64\Debug\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\ARM64\Release\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\ARM\Debug\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\ARM\Release\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\x64\Debug\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\x64\Release\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\x86\Debug\" />
    <Folder Include="000\BITs2MP3\BITs2MP3\bin\x86\Release\" />
    <Folder Include="000\BIT_IMG\BIT_IMG\bin\ARM64\Debug\" />
    <Folder Include="000\BIT_IMG\BIT_IMG\bin\ARM\Debug\" />
    <Folder Include="000\BIT_IMG\BIT_IMG\bin\x64\Debug\" />
    <Folder Include="000\CWalletSearch\CWalletSearch\bin\Release\" />
    <Folder Include="000\FarmsWar\apzyxGameService\bin\Release\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\ARM64\Debug\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\ARM64\Release\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\ARM\Debug\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\ARM\Release\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\x64\Debug\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\x64\Release\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\x86\Debug\" />
    <Folder Include="000\FarmsWar\FarmsWar\bin\x86\Release\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\ARM64\Debug\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\ARM64\Release\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\ARM\Debug\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\ARM\Release\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\x64\Debug\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\x64\Release\" />
    <Folder Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\bin\x86\Release\" />
    <Folder Include="000\Golden Way\Golden Way\bin\ARM64\Debug\" />
    <Folder Include="000\Golden Way\Golden Way\bin\ARM64\Release\" />
    <Folder Include="000\Golden Way\Golden Way\bin\ARM\Debug\" />
    <Folder Include="000\Golden Way\Golden Way\bin\ARM\Release\" />
    <Folder Include="000\Golden Way\Golden Way\bin\x64\Debug\" />
    <Folder Include="000\Golden Way\Golden Way\bin\x64\Release\" />
    <Folder Include="000\Golden Way\Golden Way\bin\x86\Release\" />
    <Folder Include="000\Golden Way\GWService\bin\Debug\" />
    <Folder Include="000\Golden Way\GWService\bin\Release\" />
    <Folder Include="000\Golden Way\probaturas\bin\Release\" />
    <Folder Include="000\Golden Way\TokensWay\bin\Debug\net6.0\" />
    <Folder Include="000\Golden Way\TokensWay\obj\Debug\net6.0\refint\" />
    <Folder Include="000\Golden Way\TokensWay\obj\Debug\net6.0\ref\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\ARM64\Debug\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\ARM64\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\ARM\Debug\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\ARM\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\Debug\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\x64\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\x86\Debug\" />
    <Folder Include="000\GOTCHA\GOTCHA.Background.MiTarea\bin\x86\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA\bin\ARM64\Debug\" />
    <Folder Include="000\GOTCHA\GOTCHA\bin\ARM64\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA\bin\ARM\Debug\" />
    <Folder Include="000\GOTCHA\GOTCHA\bin\ARM\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA\bin\x64\Release\" />
    <Folder Include="000\GOTCHA\GOTCHA\bin\x86\Release\" />
    <Folder Include="000\GOTCHA\rGOTCHA\bin\Debug\" />
    <Folder Include="000\GOTCHA\rGOTCHA\bin\Release\" />
    <Folder Include="000\hk\hk\bin\Debug\net6.0\" />
    <Folder Include="000\hk\hk\bin\Release\net6.0\" />
    <Folder Include="000\hk\hk\obj\Debug\net6.0\refint\" />
    <Folder Include="000\hk\hk\obj\Debug\net6.0\ref\" />
    <Folder Include="000\hk\hk\obj\Release\net6.0\refint\" />
    <Folder Include="000\hk\hk\obj\Release\net6.0\ref\" />
    <Folder Include="000\Maths\Maths\bin\Release\" />
    <Folder Include="000\pri\apzyxCompressor\bin\Release\" />
    <Folder Include="000\pri\apzyxDecompressor\bin\Release\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\ARM64\Debug\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\ARM64\Release\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\ARM\Debug\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\ARM\Release\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\x64\Debug\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\x64\Release\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\x86\Debug\" />
    <Folder Include="000\pri\BigIntegersCalculator\bin\x86\Release\" />
    <Folder Include="000\pri\BpC_Compresor\bin\Release\" />
    <Folder Include="000\pri\BpD_Compresor\bin\Release\" />
    <Folder Include="000\pri\comp\bin\Debug\" />
    <Folder Include="000\pri\comp\bin\Release\" />
    <Folder Include="000\pri\decomp\bin\Release\" />
    <Folder Include="000\pri\PrimeNumbersSearchWeb\bin\Debug\net6.0\" />
    <Folder Include="000\pri\PrimeNumbersSearchWeb\obj\Debug\net6.0\refint\" />
    <Folder Include="000\pri\PrimeNumbersSearchWeb\obj\Debug\net6.0\ref\" />
    <Folder Include="000\pri\PrimesDispacher\bin\Release\net6.0\" />
    <Folder Include="000\pri\PrimesDispacher\obj\Release\net6.0\refint\" />
    <Folder Include="000\pri\PrimesDispacher\obj\Release\net6.0\ref\" />
    <Folder Include="000\pri\PrimesNumbersSearch\bin\ARM\Debug\" />
    <Folder Include="000\pri\PrimesNumbersSearch\bin\x86\Debug\" />
    <Folder Include="000\pri\PrimesNumbersSearch\bin\x86\Release\" />
    <Folder Include="000\pri\pri\bin\Release\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="000\666 way\.vs\666 way\FileContentIndex\e2437204-5b4f-41c9-b871-50e6ec726ab1.vsidx" />
    <None Include="000\666 way\.vs\666 way\FileContentIndex\read.lock" />
    <None Include="000\666 way\.vs\666 way\v17\.suo" />
    <None Include="000\666 way\666 way.sln" />
    <None Include="000\666 way\666 way\666 way.csproj" />
    <None Include="000\666 way\c666wayServ\c666wayServ.csproj" />
    <None Include="000\666way\.vs\666way\config\applicationhost.config" />
    <None Include="000\666way\.vs\666way\FileContentIndex\af63eb7c-4207-41aa-a8be-c582b64e3822.vsidx" />
    <None Include="000\666way\.vs\666way\v16\.suo" />
    <None Include="000\666way\.vs\666way\v17\.suo" />
    <None Include="000\666way\666way.sln" />
    <None Include="000\666way\666way\666way.csproj" />
    <None Include="000\666way\666way\666way.csproj.user" />
    <None Include="000\666way\666way\Properties\PublishProfiles\666way - FTP.pubxml.user" />
    <None Include="000\666way\666way\Properties\PublishProfiles\666way - ReadOnly - FTP.pubxml.user" />
    <None Include="000\666way\666way\Properties\PublishProfiles\666way - Web Deploy.pubxml.user" />
    <None Include="000\addclick2\.vs\addclick2\config\applicationhost.config" />
    <None Include="000\addclick2\.vs\addclick2\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\addclick2\.vs\addclick2\v16\.suo" />
    <None Include="000\addclick2\.vs\addclick2\v16\Server\sqlite3\db.lock" />
    <None Include="000\addclick2\.vs\addclick2\v16\Server\sqlite3\storage.ide" />
    <None Include="000\addclick2\.vs\addclick\config\applicationhost.config" />
    <None Include="000\addclick2\.vs\addclick\v16\.suo" />
    <None Include="000\addclick2\.vs\addclick\v16\Server\sqlite3\db.lock" />
    <None Include="000\addclick2\.vs\addclick\v16\Server\sqlite3\storage.ide" />
    <None Include="000\addclick2\.vs\addclick\v16\Server\sqlite3\storage.ide-shm" />
    <None Include="000\addclick2\.vs\addclick\v16\Server\sqlite3\storage.ide-wal" />
    <None Include="000\addclick2\addclick2.sln" />
    <None Include="000\addclick2\addclickService\addclickService.csproj" />
    <None Include="000\addclick2\addclickService\addclickService.csproj.user" />
    <None Include="000\addclick2\addclick\addclick.csproj" />
    <None Include="000\addclick2\addclick\addclick.csproj.user" />
    <None Include="000\addclick2\apzyxService\apzyxService.csproj" />
    <None Include="000\addclick2\apzyxService\apzyxService.csproj.user" />
    <None Include="000\addclick2\blobsController\blobsController.csproj" />
    <None Include="000\addclick2\textoamp3app\textoamp3app.Android\obj\.cache\com.companyname.textoamp3app.flag" />
    <None Include="000\addclick2\textoamp3app\textoamp3app.Android\textoamp3app.Android.csproj" />
    <None Include="000\addclick2\textoamp3app\textoamp3app.Android\textoamp3app.Android.csproj.user" />
    <None Include="000\addclick2\textoamp3app\textoamp3app.iOS\textoamp3app.iOS.csproj" />
    <None Include="000\addclick2\textoamp3app\textoamp3app.UWP\textoamp3app.UWP.csproj" />
    <None Include="000\addclick2\textoamp3app\textoamp3app\textoamp3app.csproj" />
    <None Include="000\addclick2\textoamp3\Properties\PublishProfiles\conversorDeTextoAmp3 - FTP.pubxml.user" />
    <None Include="000\addclick2\textoamp3\Properties\PublishProfiles\conversorDeTextoAmp3 - Web Deploy.pubxml.user" />
    <None Include="000\addclick2\textoamp3\Properties\PublishProfiles\FolderProfile.pubxml.user" />
    <None Include="000\addclick2\textoamp3\Properties\serviceDependencies.local.json.user" />
    <None Include="000\addclick2\textoamp3\textoamp3.csproj" />
    <None Include="000\addclick2\textoamp3\textoamp3.csproj.user" />
    <None Include="000\addclick2\WcfConversorDeTextoAmp3\Properties\PublishProfiles\FolderProfile.pubxml.user" />
    <None Include="000\addclick2\WcfConversorDeTextoAmp3\WcfConversorDeTextoAmp3.csproj" />
    <None Include="000\addclick2\WcfConversorDeTextoAmp3\WcfConversorDeTextoAmp3.csproj.user" />
    <None Include="000\apzMadmanHill\.vs\apzMadmanHill\FileContentIndex\93063c68-0b28-45c8-a9c0-88dcc3a9da9e.vsidx" />
    <None Include="000\apzMadmanHill\.vs\apzMadmanHill\FileContentIndex\read.lock" />
    <None Include="000\apzMadmanHill\.vs\apzMadmanHill\v17\.suo" />
    <None Include="000\apzMadmanHill\.vs\apzMadmanHill\v17\Browse.VC.db" />
    <None Include="000\apzMadmanHill\.vs\apzMadmanHill\v17\ipch\AutoPCH\ae551ce3b31486bb\WINDOWS.ipch" />
    <None Include="000\apzMadmanHill\.vs\slnx.sqlite" />
    <None Include="000\apzMadmanHill\apzMadmanHill.sln" />
    <None Include="000\apzMadmanHill\Windows\Windows.vcxproj" />
    <None Include="000\apzMadmanHill\Windows\Windows.vcxproj.user" />
    <None Include="000\apzyxGames\.vs\apzyxGames\FileContentIndex\8025012b-fea2-447a-ae59-fa0877310fac.vsidx" />
    <None Include="000\apzyxGames\.vs\apzyxGames\FileContentIndex\bb2e1269-1f72-4a1c-80d3-7eaffe1dc557.vsidx" />
    <None Include="000\apzyxGames\.vs\apzyxGames\FileContentIndex\e1dbdf40-1e35-454e-9553-9c43c17f97e2.vsidx" />
    <None Include="000\apzyxGames\.vs\apzyxGames\v17\.suo" />
    <None Include="000\apzyxGames\apzGlib\apzGlib.csproj" />
    <None Include="000\apzyxGames\apzyxGames.sln" />
    <None Include="000\apzyxGames\apzyxGames\apzyxGames.csproj" />
    <None Include="000\apz_Image_Editor\.vs\apz_Image_Editor\FileContentIndex\4774a2e3-5172-4c79-b28c-f0087fccfaaf.vsidx" />
    <None Include="000\apz_Image_Editor\.vs\apz_Image_Editor\FileContentIndex\8bbec79b-f2c6-4f89-9f2b-357f22a6c47b.vsidx" />
    <None Include="000\apz_Image_Editor\.vs\apz_Image_Editor\FileContentIndex\9b5d4618-90d2-4e8d-8508-bad4edb3be5f.vsidx" />
    <None Include="000\apz_Image_Editor\.vs\apz_Image_Editor\v17\.suo" />
    <None Include="000\apz_Image_Editor\apz_Image_Editor.sln" />
    <None Include="000\apz_Image_Editor\apz_Image_Editor\apz_Image_Editor.csproj" />
    <None Include="000\apz_Image_Editor\apz_Image_Editor\apz_Image_Editor.csproj.user" />
    <None Include="000\apz_Image_Editor\testWriteable\testWriteable.csproj" />
    <None Include="000\bitcoinCoreMiner\.vs\bitcoinCoreMiner\FileContentIndex\3f039c33-5b7f-4061-8d2b-8b15eb5292d1.vsidx" />
    <None Include="000\bitcoinCoreMiner\.vs\bitcoinCoreMiner\v17\.suo" />
    <None Include="000\bitcoinCoreMiner\bitcoinCoreMiner.sln" />
    <None Include="000\bitcoinCoreMiner\bitcoinCoreMiner\bitcoinCoreMiner.csproj" />
    <None Include="000\BITs2MP3\.vs\BITs2MP3\FileContentIndex\74ae0cd3-a719-4b1f-a2e4-37c31fd9fa58.vsidx" />
    <None Include="000\BITs2MP3\.vs\BITs2MP3\v17\.suo" />
    <None Include="000\BITs2MP3\BITs2MP3.sln" />
    <None Include="000\BITs2MP3\BITs2MP3\BITs2MP3.csproj" />
    <None Include="000\BIT_IMG\.vs\BIT_IMG\FileContentIndex\4dddfc3a-c5da-47b8-9865-31aae8140d2f.vsidx" />
    <None Include="000\BIT_IMG\.vs\BIT_IMG\v17\.suo" />
    <None Include="000\BIT_IMG\BIT_IMG.sln" />
    <None Include="000\BIT_IMG\BIT_IMG\BIT_IMG.csproj" />
    <None Include="000\BIT_IMG\BIT_IMG\BIT_IMG.csproj.user" />
    <None Include="000\crazad\.vs\crazad\config\applicationhost.config" />
    <None Include="000\crazad\.vs\crazad\v16\.suo" />
    <None Include="000\crazad\crazad.sln" />
    <None Include="000\crazad\crazad\crazad.csproj" />
    <None Include="000\crazad\crazad\crazad.csproj.user" />
    <None Include="000\crazad\crazad\Properties\PublishProfiles\crazad - Web Deploy.pubxml.user" />
    <None Include="000\crazad\crazad\Properties\serviceDependencies.local.json.user" />
    <None Include="000\CWalletSearch\.vs\CWalletSearch\FileContentIndex\834b1f5c-34a3-4911-9aaf-63a40a1346b0.vsidx" />
    <None Include="000\CWalletSearch\.vs\CWalletSearch\FileContentIndex\a82b69f1-b086-42e7-902f-3d5a1d7a0007.vsidx" />
    <None Include="000\CWalletSearch\.vs\CWalletSearch\v17\.suo" />
    <None Include="000\CWalletSearch\CWalletSearch.sln" />
    <None Include="000\CWalletSearch\CWalletSearch\CWalletSearch.csproj" />
    <None Include="000\FarmsWar\.vs\FarmsWar\config\applicationhost.config" />
    <None Include="000\FarmsWar\.vs\FarmsWar\FileContentIndex\356ffe59-9841-4e51-a645-0e102acf169c.vsidx" />
    <None Include="000\FarmsWar\.vs\FarmsWar\FileContentIndex\3ebc9192-72e2-45ce-ba35-fad9724cad79.vsidx" />
    <None Include="000\FarmsWar\.vs\FarmsWar\FileContentIndex\6f9bb5d7-7618-4010-8514-8e7a92074497.vsidx" />
    <None Include="000\FarmsWar\.vs\FarmsWar\FileContentIndex\d2798508-759a-44cf-a5bc-d88705afc100.vsidx" />
    <None Include="000\FarmsWar\.vs\FarmsWar\FileContentIndex\e2a5a61c-62bf-4bff-bd32-7e3b52726893.vsidx" />
    <None Include="000\FarmsWar\.vs\FarmsWar\v16\.suo" />
    <None Include="000\FarmsWar\.vs\FarmsWar\v17\.suo" />
    <None Include="000\FarmsWar\apzyxGameService\apzyxGameService.csproj" />
    <None Include="000\FarmsWar\apzyxGameService\apzyxGameService.csproj.user" />
    <None Include="000\FarmsWar\apzyxGames\apzyxGames.csproj" />
    <None Include="000\FarmsWar\apzyxGames\apzyxGames.csproj.user" />
    <None Include="000\FarmsWar\apzyxGames\Properties\PublishProfiles\apzyxGames - FTP.pubxml.user" />
    <None Include="000\FarmsWar\apzyxGames\Properties\PublishProfiles\apzyxGames - FTP1.pubxml.user" />
    <None Include="000\FarmsWar\apzyxGames\Properties\PublishProfiles\apzyxGames - Web Deploy.pubxml.user" />
    <None Include="000\FarmsWar\apzyxGames\Properties\serviceDependencies.local.json.user" />
    <None Include="000\FarmsWar\FarmsWar.sln" />
    <None Include="000\FarmsWar\FarmsWar\FarmsWar.csproj" />
    <None Include="000\FarmsWar\FarmsWar\FarmsWar.csproj.user" />
    <None Include="000\FileToVideo_VideoToFile\.vs\FileToVideo_VideoToFile\FileContentIndex\fc9c6df3-216b-47a3-b498-fefaf612d973.vsidx" />
    <None Include="000\FileToVideo_VideoToFile\.vs\FileToVideo_VideoToFile\v17\.suo" />
    <None Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile.sln" />
    <None Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\FileToVideo_VideoToFile.csproj" />
    <None Include="000\FileToVideo_VideoToFile\FileToVideo_VideoToFile\FileToVideo_VideoToFile.csproj.user" />
    <None Include="000\Golden Way\.vs\Golden Way\config\applicationhost.config" />
    <None Include="000\Golden Way\.vs\Golden Way\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\Golden Way\.vs\Golden Way\FileContentIndex\3745fd22-1ce8-473d-89bf-12319b7eef88.vsidx" />
    <None Include="000\Golden Way\.vs\Golden Way\FileContentIndex\5dfb5ecc-f22c-41e8-aa2a-b69fada80072.vsidx" />
    <None Include="000\Golden Way\.vs\Golden Way\FileContentIndex\read.lock" />
    <None Include="000\Golden Way\.vs\Golden Way\v17\.futdcache.v1" />
    <None Include="000\Golden Way\.vs\Golden Way\v17\.futdcache.v2" />
    <None Include="000\Golden Way\.vs\Golden Way\v17\.suo" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.metadata.v5" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.metadata.v5.1" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.metadata.v6.1" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.projects.v2" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.projects.v5" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.projects.v5.1" />
    <None Include="000\Golden Way\.vs\ProjectEvaluation\golden way.projects.v6.1" />
    <None Include="000\Golden Way\.vs\slnx.sqlite" />
    <None Include="000\Golden Way\Golden Way.sln" />
    <None Include="000\Golden Way\Golden Way\Golden Way.csproj" />
    <None Include="000\Golden Way\GWService\GWService.csproj" />
    <None Include="000\Golden Way\probaturas\probaturas.csproj" />
    <None Include="000\Golden Way\TokensWay\Properties\PublishProfiles\tokensway - FTP.pubxml.user" />
    <None Include="000\Golden Way\TokensWay\Properties\PublishProfiles\tokensway - Web Deploy.pubxml.user" />
    <None Include="000\Golden Way\TokensWay\Properties\PublishProfiles\tokensway - Zip Deploy.pubxml.user" />
    <None Include="000\Golden Way\TokensWay\Properties\serviceDependencies.local.json.user" />
    <None Include="000\Golden Way\TokensWay\TokensWay.csproj" />
    <None Include="000\Golden Way\TokensWay\TokensWay.csproj.user" />
    <None Include="000\GOTCHA\.vs\GOTCHA\FileContentIndex\41da7e3f-19f6-47e0-8bc6-9e976661bd87.vsidx" />
    <None Include="000\GOTCHA\.vs\GOTCHA\FileContentIndex\45752798-6f26-49f7-93c7-c039e9e5caf3.vsidx" />
    <None Include="000\GOTCHA\.vs\GOTCHA\FileContentIndex\65463f7c-8042-413c-a4a3-dfe11994fd30.vsidx" />
    <None Include="000\GOTCHA\.vs\GOTCHA\FileContentIndex\727f598a-6e48-458a-a83a-d456a13f04fa.vsidx" />
    <None Include="000\GOTCHA\.vs\GOTCHA\FileContentIndex\78b0c2bc-972c-426c-ad8e-47542c071ec3.vsidx" />
    <None Include="000\GOTCHA\.vs\GOTCHA\v17\.futdcache.v2" />
    <None Include="000\GOTCHA\.vs\GOTCHA\v17\.suo" />
    <None Include="000\GOTCHA\GOTCHA.Background.MiTarea\GOTCHA.Background.MiTarea.csproj" />
    <None Include="000\GOTCHA\GOTCHA.sln" />
    <None Include="000\GOTCHA\GOTCHA\GOTCHA.csproj" />
    <None Include="000\GOTCHA\GOTCHA\GOTCHA.csproj.user" />
    <None Include="000\GOTCHA\rGOTCHA\rGOTCHA.csproj" />
    <None Include="000\GOTCHA\runGOTCHA\runGOTCHA.wapproj" />
    <None Include="000\GOTCHA\runGOTCHA\runGOTCHA.wapproj.user" />
    <None Include="000\hk\.vs\hk\config\applicationhost.config" />
    <None Include="000\hk\.vs\hk\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\hk\.vs\hk\FileContentIndex\98e5b1e8-f4fd-4add-8297-67da6cdd7f84.vsidx" />
    <None Include="000\hk\.vs\hk\FileContentIndex\read.lock" />
    <None Include="000\hk\.vs\hk\v17\.futdcache.v1" />
    <None Include="000\hk\.vs\hk\v17\.futdcache.v2" />
    <None Include="000\hk\.vs\hk\v17\.suo" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.metadata.v2" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.metadata.v5.1" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.metadata.v6.1" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.projects.v2" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.projects.v5" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.projects.v5.1" />
    <None Include="000\hk\.vs\ProjectEvaluation\hk.projects.v6.1" />
    <None Include="000\hk\hk.sln" />
    <None Include="000\hk\hk\hk.csproj" />
    <None Include="000\hk\hk\hk.csproj.user" />
    <None Include="000\hk\hk\Properties\PublishProfiles\hashkings - FTP.pubxml.user" />
    <None Include="000\hk\hk\Properties\PublishProfiles\hashkings - Web Deploy.pubxml.user" />
    <None Include="000\hk\hk\Properties\PublishProfiles\hashkings - Zip Deploy.pubxml.user" />
    <None Include="000\hk\hk\Properties\serviceDependencies.local.json.user" />
    <None Include="000\Maths\.vs\Maths\FileContentIndex\2622cd55-c882-4872-927c-f0911ee4d30c.vsidx" />
    <None Include="000\Maths\.vs\Maths\v17\.suo" />
    <None Include="000\Maths\Maths.sln" />
    <None Include="000\Maths\Maths\Maths.csproj" />
    <None Include="000\PrimeNumbersSearch\.vs\PrimeNumbersSearch\v16\.suo" />
    <None Include="000\PrimeNumbersSearch\.vs\PrimeNumbersSearch\v17\.suo" />
    <None Include="000\PrimeNumbersSearch\pnsS\pnsS.csproj" />
    <None Include="000\PrimeNumbersSearch\PrimeNumbersSearch.sln" />
    <None Include="000\PrimeNumbersSearch\PrimeNumbersSearch\PrimeNumbersSearch.csproj" />
    <None Include="000\priRem\.vs\priRem\v16\.suo" />
    <None Include="000\priRem\priRem.sln" />
    <None Include="000\priRem\priRem\priRem.csproj" />
    <None Include="000\pri\.vs\pri\config\applicationhost.config" />
    <None Include="000\pri\.vs\pri\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\pri\.vs\pri\FileContentIndex\530e510f-4b52-4576-8210-26d20df56803.vsidx" />
    <None Include="000\pri\.vs\pri\FileContentIndex\927d9a98-a11c-4e02-a248-627927fa12c6.vsidx" />
    <None Include="000\pri\.vs\pri\FileContentIndex\e9a51d5d-4833-4801-b289-7aa6aca5a18e.vsidx" />
    <None Include="000\pri\.vs\pri\v16\.suo" />
    <None Include="000\pri\.vs\pri\v17\.futdcache.v2" />
    <None Include="000\pri\.vs\pri\v17\.suo" />
    <None Include="000\pri\.vs\ProjectEvaluation\pri.metadata.v9.bin" />
    <None Include="000\pri\.vs\ProjectEvaluation\pri.projects.v9.bin" />
    <None Include="000\pri\.vs\ProjectEvaluation\pri.strings.v9.bin" />
    <None Include="000\pri\apzyxCompressor\apzyxCompressor.csproj" />
    <None Include="000\pri\apzyxCompressor\apzyxCompressor.csproj.user" />
    <None Include="000\pri\apzyxDecompressor\apzyxDecompressor.csproj" />
    <None Include="000\pri\apzyxDecompressor\apzyxDecompressor.csproj.user" />
    <None Include="000\pri\BigIntegersCalculator\BigIntegersCalculator.csproj" />
    <None Include="000\pri\BigIntegersCalculator\BigIntegersCalculator.csproj.user" />
    <None Include="000\pri\BpC_Compresor\BpC_Compresor.csproj" />
    <None Include="000\pri\BpC_Compresor\BpC_Compresor.csproj.user" />
    <None Include="000\pri\BpD_Compresor\BpD_Compresor.csproj" />
    <None Include="000\pri\BpD_Compresor\BpD_Compresor.csproj.user" />
    <None Include="000\pri\comp\comp.csproj" />
    <None Include="000\pri\comp\comp.csproj.user" />
    <None Include="000\pri\decomp\decomp.csproj" />
    <None Include="000\pri\decomp\decomp.csproj.user" />
    <None Include="000\pri\pri.sln" />
    <None Include="000\pri\priConsola\priConsola.csproj" />
    <None Include="000\pri\PrimeNumbersSearchWeb\PrimeNumbersSearchWeb.csproj" />
    <None Include="000\pri\PrimeNumbersSearchWeb\Properties\serviceDependencies.local.json.user" />
    <None Include="000\pri\PrimesDispacher\PrimesDispacher.csproj" />
    <None Include="000\pri\PrimesNumbersSearchWeb\PrimesNumbersSearchWeb.csproj" />
    <None Include="000\pri\PrimesNumbersSearchWeb\Properties\serviceDependencies.local.json.user" />
    <None Include="000\pri\PrimesNumbersSearch\PrimesNumbersSearch.csproj" />
    <None Include="000\pri\pri\pri.csproj" />
    <None Include="000\pri\TRXcomp\TRXcomp.csproj" />
    <None Include="000\pri\TXT Great Files\TXT Great Files.csproj" />
    <None Include="000\pri\WIP\WIP.csproj" />
    <None Include="000\rGOD\.vs\ProjectEvaluation\rgod.metadata.v7.bin" />
    <None Include="000\rGOD\.vs\ProjectEvaluation\rgod.projects.v7.bin" />
    <None Include="000\rGOD\.vs\rGOD\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\rGOD\.vs\rGOD\FileContentIndex\921a9960-ad2d-434f-8245-e815c8059e5c.vsidx" />
    <None Include="000\rGOD\.vs\rGOD\v17\.futdcache.v2" />
    <None Include="000\rGOD\.vs\rGOD\v17\.suo" />
    <None Include="000\rGOD\rGOD.sln" />
    <None Include="000\rGOD\rGOD\rGOD.csproj" />
    <None Include="000\seackers\.vs\ProjectEvaluation\seackers.metadata.v7.bin" />
    <None Include="000\seackers\.vs\ProjectEvaluation\seackers.projects.v7.bin" />
    <None Include="000\seackers\.vs\seackers\config\applicationhost.config" />
    <None Include="000\seackers\.vs\seackers\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\seackers\.vs\seackers\FileContentIndex\ccb6dda4-8b86-4fc3-a385-81da7a591fb3.vsidx" />
    <None Include="000\seackers\.vs\seackers\v17\.futdcache.v2" />
    <None Include="000\seackers\.vs\seackers\v17\.suo" />
    <None Include="000\seackers\seackers.sln" />
    <None Include="000\seackers\seackers\Properties\PublishProfiles\seackers - FTP.pubxml.user" />
    <None Include="000\seackers\seackers\Properties\PublishProfiles\seackers - Web Deploy.pubxml.user" />
    <None Include="000\seackers\seackers\Properties\PublishProfiles\seackers - Zip Deploy.pubxml.user" />
    <None Include="000\seackers\seackers\Properties\serviceDependencies.local.json.user" />
    <None Include="000\seackers\seackers\seackers - Backup.csproj" />
    <None Include="000\seackers\seackers\seackers.csproj" />
    <None Include="000\seackers\seackers\seackers.csproj.user" />
    <None Include="000\TokensWay\.vs\ProjectEvaluation\tokensway.metadata.v5.1" />
    <None Include="000\TokensWay\.vs\ProjectEvaluation\tokensway.projects.v5.1" />
    <None Include="000\TokensWay\.vs\TokensWay\config\applicationhost.config" />
    <None Include="000\TokensWay\.vs\TokensWay\DesignTimeBuild\.dtbcache.v2" />
    <None Include="000\TokensWay\.vs\TokensWay\FileContentIndex\4a110b29-022f-48dd-a493-bd899069afac.vsidx" />
    <None Include="000\TokensWay\.vs\TokensWay\FileContentIndex\91a7a08d-422e-47d5-83bb-d041b0fba916.vsidx" />
    <None Include="000\TokensWay\.vs\TokensWay\FileContentIndex\af92cfaf-0e05-41e5-b622-3925496d309b.vsidx" />
    <None Include="000\TokensWay\.vs\TokensWay\FileContentIndex\d33598f8-3e0d-42d8-be0f-225989987f00.vsidx" />
    <None Include="000\TokensWay\.vs\TokensWay\FileContentIndex\d9080516-4add-475d-8d66-bfc48f0c210a.vsidx" />
    <None Include="000\TokensWay\.vs\TokensWay\FileContentIndex\read.lock" />
    <None Include="000\TokensWay\.vs\TokensWay\v17\.futdcache.v2" />
    <None Include="000\TokensWay\.vs\TokensWay\v17\.suo" />
    <None Include="000\TokensWay\.vs\TokensWay\v17\fileList.bin" />
    <None Include="000\TokensWay\TokensWay.sln" />
    <None Include="000\TokensWay\TokensWay\Properties\serviceDependencies.local.json.user" />
    <None Include="000\TokensWay\TokensWay\TokensWay.csproj" />
    <None Include="000\TokensWay\TokensWay\TokensWay.csproj.user" />
    <None Include="000\universalsemiotics\.vs\universalsemiotics\config\applicationhost.config" />
    <None Include="000\universalsemiotics\.vs\universalsemiotics\FileContentIndex\73fd229b-151e-4866-a32f-020b1da680dc.vsidx" />
    <None Include="000\universalsemiotics\.vs\universalsemiotics\FileContentIndex\read.lock" />
    <None Include="000\universalsemiotics\.vs\universalsemiotics\v16\.suo" />
    <None Include="000\universalsemiotics\.vs\universalsemiotics\v17\.suo" />
    <None Include="000\universalsemiotics\universalsemiotics.sln" />
    <None Include="000\universalsemiotics\universalsemioticsBlobController\universalsemioticsBlobController.csproj" />
    <None Include="000\universalsemiotics\universalsemioticsService\universalsemioticsService.csproj" />
    <None Include="000\universalsemiotics\universalsemiotics\Properties\PublishProfiles\universalsemiotics - FTP.pubxml.user" />
    <None Include="000\universalsemiotics\universalsemiotics\Properties\PublishProfiles\universalsemiotics - Web Deploy.pubxml.user" />
    <None Include="000\universalsemiotics\universalsemiotics\Properties\serviceDependencies.local.json.user" />
    <None Include="000\universalsemiotics\universalsemiotics\Properties\serviceDependencies.universalsemiotics - Web Deploy.json.user" />
    <None Include="000\universalsemiotics\universalsemiotics\universalsemiotics.csproj" />
    <None Include="000\universalsemiotics\universalsemiotics\universalsemiotics.csproj.user" />
  </ItemGroup>
</Project>