//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWP000
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicidadD
    {
        public System.Guid Id { get; set; }
        public string image { get; set; }
        public string urlD { get; set; }
        public string emailD { get; set; }
        public bool validado { get; set; }
        public bool publicado { get; set; }
        public decimal precio { get; set; }
    }
}
namespace UWP000
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicidadI
    {
        public System.Guid Id { get; set; }
        public string image { get; set; }
        public string urlD { get; set; }
        public string emailD { get; set; }
        public bool validado { get; set; }
        public bool publicado { get; set; }
        public decimal precio { get; set; }
    }
}
